#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

build_pkgroll() {
  set -x
  rm -rf dist
  mkdir dist
  # https://esbuild.github.io/api/#target
  npx pkgroll --target=es2020
  cp src/bin.cjs ./dist
  rm dist/cli.mjs
  set +x
}

"$@"
